/*=========================================================
	
	mfstrings.h
	
	MacroFireì‡Ç≈égópÇ∑ÇÈï∂éöóÒíËêîÅB
	
=========================================================*/
#ifndef MFSTRINGS_H
#define MFSTRINGS_H

#define MF_STR_TITLE "MacroFire %s In-game menu"

#define MF_STR_LIMIT_WEBBROWSER "Cannot use this function on the web-browser."

#define MF_STR_ERROR                     "Error"
#define MF_STR_ERROR_INVALID_CONF        "Not a valid MacroFire configuration."
#define MF_STR_ERROR_UNSUPPORTED_VERSION "Unsupported file version."
#define MF_STR_ERROR_NOT_ENOUGH_MEMORY   "Not enough memory."
#define MF_STR_ERROR_COMMON              "An error occurred while processing."
#define MF_STR_ERROR_DOPEN_TIMEOUT_TITLE "Read timed out"
#define MF_STR_ERROR_DOPEN_TIMEOUT       "MemoryStick is currently busy.\nPlease try again later."

#define MF_STR_CTRL_ON            "ON"
#define MF_STR_CTRL_OFF           "OFF"
#define MF_STR_CTRL_MOVE          "Move"
#define MF_STR_CTRL_PAGEMOVE      "PageMove"
#define MF_STR_CTRL_BACK          "Back"
#define MF_STR_CTRL_TOGGLE_SWITCH "Toggle switch"
#define MF_STR_CTRL_ENTER         "Enter"
#define MF_STR_CTRL_ASSIGN        "Assign"
#define MF_STR_CTRL_DECREASE      "Decrease"
#define MF_STR_CTRL_INCREASE      "Increase"
#define MF_STR_CTRL_EDIT          "Edit"
#define MF_STR_CTRL_CHANGE_OPTION "Change option"
#define MF_STR_CTRL_EXECUTE       "Execute"
#define MF_STR_CTRL_CHOOSEFILE    "Choose file"
#define MF_STR_CTRL_SAVEFILE      "Save file"
#define MF_STR_CTRL_EXIT          "Exit"

#define MF_STR_SAVE    "Save"
#define MF_STR_LOAD    "Load"
#define MF_STR_SAVING  "Saving %s..."
#define MF_STR_LOADING "Loading %s..."

#define MF_STR_HOME_MACROFIRE_ENGINE        "MacroFire Engine"
#define MF_STR_HOME_MACROFIRE_PREFERENCE    "Preference"
#define MF_STR_HOME_SET_MENU_BUTTON         "Buttons to launch the menu"
#define MF_STR_HOME_SET_TOGGLE_BUTTON       "Buttons to toggle the engine state"
#define MF_STR_HOME_STAT_NOTIFICATION       "Status notification"
#define MF_STR_HOME_ANALOG_STICK_ADJUSTMENT "Analog stick sensitivity adjustment"
#define MF_STR_HOME_FUNCTION                "Functions"
#define MF_STR_HOME_RETURN_TO_GAME          "Returning to the game..."
#define MF_STR_HOME_LOW_MEMORY_MODE         "<Low Memory Mode>"

#define MF_STR_FUNCTION_REMAP     "Remap settings"
#define MF_STR_FUNCTION_RAPIDFIRE "Rapidfire settings"
#define MF_STR_FUNCTION_MACRO     "Macro settings"

#define MF_STR_ASA_DESC          "Analog stick sensitivity adjustment."
#define MF_STR_ASA_MOVEMENT      "Analog stick movement"
#define MF_STR_ASA_DEADZONE      "Deadzone radius"
#define MF_STR_ASA_SENSITIVITY   "Sensitivity    "
#define MF_STR_ASA_ORIGIN_X      "Origin X-coordinate"
#define MF_STR_ASA_ORIGIN_Y      "Origin Y-coordinate"
#define MF_STR_ASA_TEST_DIR      "Test of analog stick direction:"
#define MF_STR_ASA_TEST_MOVE     "Test of analog stcik movement:"
#define MF_STR_ASA_TEST_MOVE_RAW "     Raw coordinate"
#define MF_STR_ASA_TEST_MOVE_ADJ "Adjusted coordinate"

#define MF_STR_REMAP_DESC               "Remapping buttons list."
#define MF_STR_REMAP_SUGGEST            "<Press TRIANGLE(%s) to add a new remap>"
#define MF_STR_REMAP_BUTTON             "Remapping to"
#define MF_STR_REMAP_BUTTON_DISABLE     "Disable"
#define MF_STR_REMAP_CLEAR              "Clear"
#define MF_STR_REMAP_CTRL_SWITCH_COLUMN "Switch column"
#define MF_STR_REMAP_CLEAR_WARN_TITLE   "Warning"
#define MF_STR_REMAP_CLEAR_WARN_MSG     "Clearing all remap entries.\nAre you sure?"
#define MF_STR_REMAP_CTRL_ADD           "Add"
#define MF_STR_REMAP_CTRL_DELETE        "Delete"
#define MF_STR_REMAP_CTRL_EDIT_REMAP    "Edit remap buttons"
#define MF_STR_REMAP_DIAGBUTTON_REAL    "Set real buttons"
#define MF_STR_REMAP_DIAGBUTTON_REMAP   "Set remap buttons"
#define MF_STR_REMAP_DIAGGETFN_SAVE     "Save remap configuration"
#define MF_STR_REMAP_DIAGGETFN_LOAD     "Load remap configuration"

#define MF_STR_RAPIDFIRE_DESC                      "Please choose a rapidfire mode per buttons." 
#define MF_STR_RAPIDFIRE_MODE_LABEL                "Mode"
#define MF_STR_RAPIDFIRE_BUTTON_TRIANGLE           "Triangle"
#define MF_STR_RAPIDFIRE_BUTTON_CIRCLE             "Circle  "
#define MF_STR_RAPIDFIRE_BUTTON_CROSS              "Cross   "
#define MF_STR_RAPIDFIRE_BUTTON_SQUARE             "Square  "
#define MF_STR_RAPIDFIRE_BUTTON_LTRIGGER           "L-trig  "
#define MF_STR_RAPIDFIRE_BUTTON_RTRIGGER           "R-trig  "
#define MF_STR_RAPIDFIRE_BUTTON_UP                 "Up    "
#define MF_STR_RAPIDFIRE_BUTTON_RIGHT              "Right "
#define MF_STR_RAPIDFIRE_BUTTON_DOWN               "Down  "
#define MF_STR_RAPIDFIRE_BUTTON_LEFT               "Left  "
#define MF_STR_RAPIDFIRE_BUTTON_START              "Start "
#define MF_STR_RAPIDFIRE_BUTTON_SELECT             "Select"
#define MF_STR_RAPIDFIRE_WAITCONTROL_LABEL         "Wait control"
#define MF_STR_RAPIDFIRE_WAITCONTROL_PRESS_DELAY   "Press delay  "
#define MF_STR_RAPIDFIRE_WAITCONTROL_RELEASE_DELAY "Release delay"
#define MF_STR_RAPIDFIRE_FILE_LABEL                "File"
#define MF_STR_RAPIDFIRE_MANUAL_NORMAL             "Normal    : Nothing to do."
#define MF_STR_RAPIDFIRE_MANUAL_RAPID              "Rapid     : Rapidfire while pressing."
#define MF_STR_RAPIDFIRE_MANUAL_AUTORAPID          "Auto-Rapid: Always rapidfire."
#define MF_STR_RAPIDFIRE_MANUAL_HOLD               "Hold      : Toggle the hold/release state."
#define MF_STR_RAPIDFIRE_MANUAL_AUTOHOLD           "Auto-Hold : Always to hold."
#define MF_STR_RAPIDFIRE_DIAGGETFN_SAVE            "Save rapidfire preference"
#define MF_STR_RAPIDFIRE_DIAGGETFN_LOAD            "Load rapidfire preference"

#define MF_STR_MACRO_DESC                  "Please choose a operation."
#define MF_STR_MACRO_SLOT_ADD              "Add macro"
#define MF_STR_MACRO_SLOT_REMOVE           "Remove macro"
#define MF_STR_MACRO_SLOT                  "Macro"
#define MF_STR_MACRO_PREF_LABEL            "Preference"
#define MF_STR_MACRO_PREF_RUN_STOP         "Buttons to run/stop the macro"
#define MF_STR_MACRO_PREF_LOOP_NUM         "Number of loop"
#define MF_STR_MACRO_CONTROL_LABEL         "Control"
#define MF_STR_MACRO_CONTROL_RUN           "Run"
#define MF_STR_MACRO_CONTROL_STOP          "Stop"
#define MF_STR_MACRO_CONTROL_EDIT          "Edit"
#define MF_STR_MACRO_CONTROL_CLEAR         "Clear"
#define MF_STR_MACRO_RECORD_LABEL          "Realtime recording"
#define MF_STR_MACRO_RECORD_START          "Start"
#define MF_STR_MACRO_RECORD_APPEND         "Append"
#define MF_STR_MACRO_RECORD_STOP           "Stop"
#define MF_STR_MACRO_RECORD_ANALOG         "Recording analog stick movement"
#define MF_STR_MACRO_FILE_LABEL            "File"
#define MF_STR_MACRO_STAT_RECORDING        "Recording"
#define MF_STR_MACRO_STAT_RUNNING          "Running"
#define MF_STR_MACRO_STAT_AVAILABLE        "Available"
#define MF_STR_MACRO_STAT_UNASSIGNED       "Unassigned"
#define MF_STR_MACRO_STAT_WAITING          "Waiting"
#define MF_STR_MACRO_CTRL_PREV             "Prev"
#define MF_STR_MACRO_CTRL_NEXT             "Next"
#define MF_STR_MACRO_MSG_SLOT_ADD_TITLE    MF_STR_MACRO_SLOT_ADD
#define MF_STR_MACRO_MSG_SLOT_ADD          "Added new macro slot."
#define MF_STR_MACRO_MSG_SLOT_REMOVE_TITLE MF_STR_MACRO_SLOT_REMOVE
#define MF_STR_MACRO_MSG_SLOT_REMOVE_WARN  "The recorded macro will be removed.\nAre you sure?"
#define MF_STR_MACRO_MSG_SLOT_REMOVE       "Removed current macro slot."
#define MF_STR_MACRO_CTRL_EDIT_NAME        "Edit macro name"
#define MF_STR_MACRO_DIAGSOSK_NAME         "Macro name"
#define MF_STR_MACRO_LOOP_INFINITY         "Infinity"
#define MF_STR_MACRO_CLEAR_WARN_TITLE      "Warning"
#define MF_STR_MACRO_CLEAR_WARN_MSG        "Clearing macro.\nAre you sure?"
#define MF_STR_MACRO_DIAGGETFN_SAVE        "Save macro"
#define MF_STR_MACRO_DIAGGETFN_LOAD        "Load macro"
#define MF_STR_MACRO_ENGINE_IS_OFF         "You must toggle to \"ON\" the MacroFire Engine."
#define MF_STR_MACRO_OVMSG_START           "Starting macro %d [%s]"
#define MF_STR_MACRO_OVMSG_HALT            "Macro halted"
#define MF_STR_MACRO_OVMSG_FINISH          "Macro finished"

#define MF_STR_MACROEDITOR_CTRL_EDIT                       "Edit"
#define MF_STR_MACROEDITOR_CTRL_CHANGE                     "Change"
#define MF_STR_MACROEDITOR_CTRL_DELETE                     "Delete"
#define MF_STR_MACROEDITOR_CTRL_INS_BEFORE                 "Insert before"
#define MF_STR_MACROEDITOR_CTRL_INS_AFTER                  "Insert after"
#define MF_STR_MACROEDITOR_CMD_RAPIDFIRE_START_EDIT_BUTTON "Edit buttons"
#define MF_STR_MACROEDITOR_CMD_RAPIDFIRE_START_EDIT_PD     "Edit press delay(PD)"
#define MF_STR_MACROEDITOR_CMD_RAPIDFIRE_START_EDIT_RD     "Edit release delay(RD)"
#define MF_STR_MACROEDITOR_CMD_ANALOG_MOVE_EDIT_X          "Edit X-coordinate"
#define MF_STR_MACROEDITOR_CMD_ANALOG_MOVE_EDIT_Y          "Edit Y-coordinate"

#endif
